{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "from sqlalchemy import create_engine\n",
    "import pyodbc"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Database credentials\n",
    "driver = '{ODBC Driver 17 for SQL Server}'\n",
    "server1 = 'LAPTOP-ALOSMCSV' \n",
    "database1 = 'AdventureWorks2022;'\n",
    "\n",
    "server2 = 'LAPTOP-ALOSMCSV' \n",
    "database2 = 'AdventureWorksDW2019;'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Connect SQL Server Management Studio to Python\n",
    "conn = pyodbc.connect('DRIVER=' + driver + ';SERVER=' + server1 + '\\SQLEXPRESS' + ';DATABASE=' + database1 + ';SERVER=' + server2 + '\\SQLEXPRESS' +';DATABASE=' + database2 + ';Trusted_Connection=yes;')\n",
    "cursor = conn.cursor() "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Show Data 1: \n",
      "\n",
      "('Accounting Manager', datetime.datetime(2008, 4, 30, 0, 0))\n",
      "('Assistant Sales Agent', datetime.datetime(2008, 4, 30, 0, 0))\n",
      "('Assistant Sales Representative', datetime.datetime(2008, 4, 30, 0, 0))\n",
      "('Coordinator Foreign Markets', datetime.datetime(2008, 4, 30, 0, 0))\n",
      "('Export Administrator', datetime.datetime(2008, 4, 30, 0, 0))\n",
      "('International Marketing Manager', datetime.datetime(2008, 4, 30, 0, 0))\n",
      "('Marketing Assistant', datetime.datetime(2008, 4, 30, 0, 0))\n",
      "('Marketing Manager', datetime.datetime(2008, 4, 30, 0, 0))\n",
      "('Marketing Representative', datetime.datetime(2008, 4, 30, 0, 0))\n",
      "('Order Administrator', datetime.datetime(2008, 4, 30, 0, 0))\n",
      "('Owner', datetime.datetime(2008, 4, 30, 0, 0))\n",
      "('Owner/Marketing Assistant', datetime.datetime(2008, 4, 30, 0, 0))\n",
      "('Product Manager', datetime.datetime(2008, 4, 30, 0, 0))\n",
      "('Purchasing Agent', datetime.datetime(2008, 4, 30, 0, 0))\n",
      "('Purchasing Manager', datetime.datetime(2008, 4, 30, 0, 0))\n",
      "('Regional Account Representative', datetime.datetime(2008, 4, 30, 0, 0))\n",
      "('Sales Agent', datetime.datetime(2008, 4, 30, 0, 0))\n",
      "('Sales Associate', datetime.datetime(2008, 4, 30, 0, 0))\n",
      "('Sales Manager', datetime.datetime(2008, 4, 30, 0, 0))\n",
      "('Sales Representative', datetime.datetime(2008, 4, 30, 0, 0))\n"
     ]
    }
   ],
   "source": [
    "# Extract data from AdventureWorks2022\n",
    "print(\"Show Data 1: \\n\")\n",
    "sql_query1 = \"SELECT TOP (1000) [Name],[ModifiedDate] FROM [AdventureWorks2022].[Person].[ContactType]\"\n",
    "cursor.execute(sql_query1)\n",
    "for row in cursor:\n",
    "    print(row)\n",
    "\n",
    "results1 = cursor.fetchall()\n",
    "df1 = pd.DataFrame(results1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Show Final Data 1: \n",
      "\n",
      "('Accounting Manager', '2008-04-30')\n",
      "('Assistant Sales Agent', '2008-04-30')\n",
      "('Assistant Sales Representative', '2008-04-30')\n",
      "('Coordinator Foreign Markets', '2008-04-30')\n",
      "('Export Administrator', '2008-04-30')\n",
      "('International Marketing Manager', '2008-04-30')\n",
      "('Marketing Assistant', '2008-04-30')\n",
      "('Marketing Manager', '2008-04-30')\n",
      "('Marketing Representative', '2008-04-30')\n",
      "('Order Administrator', '2008-04-30')\n",
      "('Owner', '2008-04-30')\n",
      "('Owner/Marketing Assistant', '2008-04-30')\n",
      "('Product Manager', '2008-04-30')\n",
      "('Purchasing Agent', '2008-04-30')\n",
      "('Purchasing Manager', '2008-04-30')\n",
      "('Regional Account Representative', '2008-04-30')\n",
      "('Sales Agent', '2008-04-30')\n",
      "('Sales Associate', '2008-04-30')\n",
      "('Sales Manager', '2008-04-30')\n",
      "('Sales Representative', '2008-04-30')\n"
     ]
    }
   ],
   "source": [
    "# Extract data from AdventureWorks2022\n",
    "print(\"Show Final Data 1: \\n\")\n",
    "delete_null = \"SELECT TOP (1000) [Name],CONVERT(varchar(10), CAST([ModifiedDate] AS DATE), 120) AS ModifiedDate FROM [AdventureWorks2022].[Person].[ContactType]\"\n",
    "cursor.execute(delete_null)\n",
    "for row in cursor:\n",
    "    print(row)\n",
    "\n",
    "final_results1 = cursor.fetchall()\n",
    "df1_final = pd.DataFrame(final_results1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Show Data 2: \n",
      "\n",
      "('Mountain Bikes', 'Bicicleta de montaña', 'VTT')\n",
      "('Road Bikes', 'Bicicleta de carretera', 'Vélo de route')\n",
      "('Touring Bikes', 'Bicicleta de paseo', 'Vélo de randonnée')\n",
      "('Handlebars', 'Barra', \"Barre d'appui\")\n",
      "('Bottom Brackets', 'Eje de pedalier', 'Axe de pédalier')\n",
      "('Brakes', 'Frenos', 'Freins')\n",
      "('Chains', 'Cadena', 'Chaîne')\n",
      "('Cranksets', 'Bielas', 'Pédalier')\n",
      "('Derailleurs', 'Desviador', 'Dérailleur')\n",
      "('Forks', 'Horquilla', 'Fourche')\n",
      "('Headsets', 'Dirección', 'Jeu de direction')\n",
      "('Mountain Frames', 'Cuadro de montaña', 'Cadre de VTT')\n",
      "('Pedals', 'Pedal', 'Pédale')\n",
      "('Road Frames', 'Cuadro de carretera', 'Cadre de vélo de route')\n",
      "('Saddles', 'Sillín', 'Selle')\n",
      "('Touring Frames', 'Cuadro de paseo', 'Cadre de vélo de randonnée')\n",
      "('Wheels', 'Rueda', 'Roue')\n",
      "('Bib-Shorts', 'Culote corto', 'Cuissards avec bretelles')\n",
      "('Caps', 'Gorra', 'Casquette')\n",
      "('Gloves', 'Guantes', 'Gants')\n",
      "('Jerseys', 'Jersey', 'Maillot')\n",
      "('Shorts', 'Pantalones cortos', 'Cuissards')\n",
      "('Socks', 'Calcetines', 'Chaussettes')\n",
      "('Tights', 'Mallas', 'Collants')\n",
      "('Vests', 'Camiseta', 'Veste')\n",
      "('Bike Racks', 'Portabicicletas', 'Porte-vélo')\n",
      "('Bike Stands', 'Soporte para bicicletas', 'Range-vélo')\n",
      "('Bottles and Cages', 'Portabotellas y botella', 'Bidon et porte-bidon')\n",
      "('Cleaners', 'Limpiador', 'Nettoyant')\n",
      "('Fenders', 'Guardabarros', 'Garde-boue')\n",
      "('Helmets', 'Casco', 'Casque')\n",
      "('Hydration Packs', 'Sistema de hidratación', \"Sac d'hydratation\")\n",
      "('Lights', 'Luz', 'Éclairage')\n",
      "('Locks', 'Candado', 'Antivol')\n",
      "('Panniers', 'Cesta', 'Sacoche')\n",
      "('Pumps', 'Bomba', 'Pompe')\n",
      "('Tires and Tubes', 'Cubierta y cámara', 'Pneu et chambre à air')\n"
     ]
    }
   ],
   "source": [
    "# Extract data from AdventureWorksDW2019\n",
    "print(\"Show Data 2: \\n\")\n",
    "sql_query2 = \"SELECT TOP (1000) [EnglishProductSubcategoryName],[SpanishProductSubcategoryName],[FrenchProductSubcategoryName] FROM [AdventureWorksDW2019].[dbo].[DimProductSubcategory]\"  \n",
    "cursor.execute(sql_query2) \n",
    "for row in cursor:\n",
    "    print(row)\n",
    "\n",
    "results2 = cursor.fetchall()\n",
    "df2 = pd.DataFrame(results2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "An error occurred: (psycopg2.OperationalError) connection to server at \"localhost\" (::1), port 5432 failed: FATAL:  password authentication failed for user \"etl\"\n",
      "\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 145, in __init__\n",
      "    self._dbapi_connection = engine.raw_connection()\n",
      "                             ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3288, in raw_connection\n",
      "    return self.pool.connect()\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 452, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 1267, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 716, in checkout\n",
      "    rec = pool._do_get()\n",
      "          ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 169, in _do_get\n",
      "    with util.safe_reraise():\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 167, in _do_get\n",
      "    return self._create_connection()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 393, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 678, in __init__\n",
      "    self.__connect()\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 902, in __connect\n",
      "    with util.safe_reraise():\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 898, in __connect\n",
      "    self.dbapi_connection = connection = pool._invoke_creator(self)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 637, in connect\n",
      "    return dialect.connect(*cargs, **cparams)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 615, in connect\n",
      "    return self.loaded_dbapi.connect(*cargs, **cparams)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\psycopg2\\__init__.py\", line 122, in connect\n",
      "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "psycopg2.OperationalError: connection to server at \"localhost\" (::1), port 5432 failed: FATAL:  password authentication failed for user \"etl\"\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\62877\\AppData\\Local\\Temp\\ipykernel_26692\\3377388955.py\", line 16, in <module>\n",
      "    df.to_sql('my_table', engine, if_exists='replace', index=False)\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\pandas\\core\\generic.py\", line 2987, in to_sql\n",
      "    return sql.to_sql(\n",
      "           ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\pandas\\io\\sql.py\", line 695, in to_sql\n",
      "    return pandas_sql.to_sql(\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\pandas\\io\\sql.py\", line 1728, in to_sql\n",
      "    table = self.prep_table(\n",
      "            ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\pandas\\io\\sql.py\", line 1631, in prep_table\n",
      "    table.create()\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\pandas\\io\\sql.py\", line 827, in create\n",
      "    if self.exists():\n",
      "       ^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\pandas\\io\\sql.py\", line 814, in exists\n",
      "    return self.pd_sql.has_table(self.name, self.schema)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\pandas\\io\\sql.py\", line 1760, in has_table\n",
      "    insp = sqlalchemy_inspect(self.connectable)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\inspection.py\", line 145, in inspect\n",
      "    ret = reg(subject)\n",
      "          ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\engine\\reflection.py\", line 303, in _engine_insp\n",
      "    return Inspector._construct(Inspector._init_engine, bind)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\engine\\reflection.py\", line 236, in _construct\n",
      "    init(self, bind)\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\engine\\reflection.py\", line 247, in _init_engine\n",
      "    engine.connect().close()\n",
      "    ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3264, in connect\n",
      "    return self._connection_cls(self)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 147, in __init__\n",
      "    Connection._handle_dbapi_exception_noconnection(\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 2426, in _handle_dbapi_exception_noconnection\n",
      "    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 145, in __init__\n",
      "    self._dbapi_connection = engine.raw_connection()\n",
      "                             ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3288, in raw_connection\n",
      "    return self.pool.connect()\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 452, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 1267, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 716, in checkout\n",
      "    rec = pool._do_get()\n",
      "          ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 169, in _do_get\n",
      "    with util.safe_reraise():\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 167, in _do_get\n",
      "    return self._create_connection()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 393, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 678, in __init__\n",
      "    self.__connect()\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 902, in __connect\n",
      "    with util.safe_reraise():\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 898, in __connect\n",
      "    self.dbapi_connection = connection = pool._invoke_creator(self)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 637, in connect\n",
      "    return dialect.connect(*cargs, **cparams)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 615, in connect\n",
      "    return self.loaded_dbapi.connect(*cargs, **cparams)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\62877\\anaconda3\\envs\\myenv\\Lib\\site-packages\\psycopg2\\__init__.py\", line 122, in connect\n",
      "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at \"localhost\" (::1), port 5432 failed: FATAL:  password authentication failed for user \"etl\"\n",
      "\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n"
     ]
    }
   ],
   "source": [
    "#Transform to dataframe\n",
    "import traceback\n",
    "\n",
    "try:\n",
    "    df = pd.concat([df1_final, df2])\n",
    "    \n",
    "    # Environment PG\n",
    "    pg_user = \"etl\"\n",
    "    pg_pass = \"etlpipe\"\n",
    "    pg_db = \"etlpipe_db\"\n",
    "    \n",
    "    # Create SQLAlchemy engine to connect to PostgreSQL\n",
    "    engine = create_engine(f'postgresql://{pg_user}:{pg_pass}@localhost:5432//{pg_db}')\n",
    "    \n",
    "    # Load the DataFrame into PostgreSQL\n",
    "    df.to_sql('my_table', engine, if_exists='replace', index=False) \n",
    "\n",
    "    print(\"Data loaded into PostgreSQL\")\n",
    "except Exception as e:\n",
    "    print(\"An error occurred:\", e)\n",
    "    traceback.print_exc()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "myenv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
